### ISSUE TITLE
transformers 4.22.1 fails with accelerate

### ISSUE THREAD

**Issue by mayank31398** [huggingface/transformers-bloom-inference#17]
@stas00 fyi
the current memory map {0, 51, ...} is failing for transformers 4.22.1 with the error:
some params were offloaded to disk due to the current device_map. Please provide offload folder.

Seems like a lot of things changes from 4.21.2 to 4.22.1.
I can work on fixing this. Any ideas how to go about it? Maybe just add 1 GB to first GPU (seems like the most easiest)?

**Comment by stas00** [comment]
Isn't that error coming from `accelerate` I would check that first as the possible source - possibly some logic has changed recently?

but yes, by all means, please feel free to experience and if still unresolved I'd file an issue at Accelerate

**Comment by mayank31398** [comment]
@sgugger fyi, do you think this bug is coming from accelerate?
This issue is seen when memory map for 0th GPU is 0 GB.

**Comment by mayank31398** [comment]
filed in accelerate: https://github.com/huggingface/accelerate/issues/762
