### ISSUE TITLE
transformers_bloom_parallel link 404

### ISSUE THREAD

**Issue by zcrypt0** [huggingface/transformers-bloom-inference#2]
https://github.com/huggingface/transformers_bloom_parallel

This link in the README.md leads to a 404 currently.

Did the repo get deleted?

**Comment by mayank31398** [comment]
@stas00

**Comment by stas00** [comment]
oh, wait, it's private! 

thank you for the heads up, @mayank31398!

@thomas21, would you like to make it public or should I remove the link for now? I linked to it from https://github.com/huggingface/transformers-bloom-inferenc Thank you!

**Comment by thomasw21** [comment]
Good point. Let's remove it for now, we can set up a cleaner repo (it's my WIP repo where I explore a few things so everything is a bit messy) once we share @Narsil 's work that's built on top of that solution.

**Comment by stas00** [comment]
as requested link removed.

> The reason why I think it's better to clean it up is I believe the purpose of sharing would be to make it somewhat useable and this would require some (lightweight, but low in my priority list) type of cleaning. If there's a strong want I can focus on that.

It's totally your call, Thomas. Since we have a really fast solution with DS-Inference I think there is absolutely no rush.

If you want an incentive to clean it up I'd make the repo public first and when someone tries to use it they could drive the need to make it easy to use :)

**Comment by zcrypt0** [comment]
I have experience with CUDA and would be interested to gain access to the repo if possible @thomasw21 

For advanced users, who are willing to dig into the code, getting access to your work and trying things out, even before the code is generally usable, is really great.
