### ISSUE TITLE
Inference with 4*A100 GPUs

### ISSUE THREAD

**Issue by xiang-deng** [huggingface/transformers-bloom-inference#26]
I ran into a few issues running the inference server with 4*A100 GPUs with `microsoft/bloom-deepspeed-inference-int8` but was able to make it work with a few tweaks. Hope it is helpful for others.

1. Somehow I still need the hack in https://github.com/huggingface/transformers-bloom-inference/pull/21
2. change tensor_parallel to 4 https://github.com/huggingface/transformers-bloom-inference/blob/cd193dbd7fe6ac0d1b97b2dd623f384249fb0ca0/bloom-inference-server/models/ds_inference.py#L99

**Comment by mayank31398** [comment]
Yeah, that hack is still needed @xiang-deng 
https://github.com/huggingface/transformers-bloom-inference/pull/25 -> this PR introduces a lot of changes. Can you try with this? I think you should be able to make it work too.
Let me know if there are any issues

**Comment by xiang-deng** [comment]
Thanks for the update, the new scripts work. But I think there is an issue in the readme for environment setup. It suggests `deepspeed-mii==0.0.2` which depends on `transformers==4.21.2`, but the `"device_map": "balanced_low_0"` requires a higher version transformers. Install from the deepspeed-mii github could work.

**Comment by mayank31398** [comment]
Thanks for pointing this out.
Ill update the readme
