### ISSUE TITLE
Newly added model_class argument has not been reflected to server code

### ISSUE THREAD

**Issue by koreyou** [huggingface/transformers-bloom-inference#33]
Argument `model_class` has been introduced in #29.
However, it has not been reflected to [deployment code](https://github.com/huggingface/transformers-bloom-inference/blob/dffb799f9d00f8b3228dfdfe7b88727a55b889c6/inference_server/model_handler/deployment.py#L90) so `make bloom-176b` fails with argument error.

Also, `model_class` is not reflected to [README](https://github.com/huggingface/transformers-bloom-inference/blob/dffb799f9d00f8b3228dfdfe7b88727a55b889c6/inference_server/README.md) so example codes fail as well.

**Comment by mayank31398** [comment]
BLOOM-176B is working fine for me @koreyou .
Sorry, for the old README. I will update it.
Can you look at the makefile: https://github.com/huggingface/transformers-bloom-inference/blob/main/Makefile

run `make bloom-176b`
