### ISSUE TITLE
[Question] 4-GPU shard `microsoft/bloom-deepspeed-inference-int8`

### ISSUE THREAD

**Issue by zcrypt0** [huggingface/transformers-bloom-inference#4]
On the hf model page for `microsoft/bloom-deepspeed-inference-int8` it states that those weights are broken up into shards for 8 gpus.

In this repo, there is an example using 4 gpus with that model.

My question is whether there is a benefit to producing (manually) a 4-GPU sharded version, or if there would be any difference at all.

/cc @stas00

**Comment by stas00** [comment]
it is still ok to use the same repo with 4 gpus. once loaded it's all the same, perhaps loading will be slightly slower but I doubt so since 4 processes will still do faster IO than 8 I'm pretty sure.

But yes, you can always save the 4-gpu version and use that as well.

**Comment by zcrypt0** [comment]
Thanks for the quick reply.

**Comment by zcrypt0** [comment]
@stas00 are there any docs on how to go about creating sharded int8 weights oneself?

I assume they are based on the bitsandbytes BLOOM int8 weights, but am not sure how you loaded them into Deepspeed for sharding.

**Comment by mayank31398** [comment]
@zcrypt0 I haven't quantized a model myself.
But this example should work I think:
https://github.com/microsoft/DeepSpeedExamples/blob/master/model_compression/gpt2/bash_script/run_zero_quant.sh

**Comment by RezaYazdaniAminabadi** [comment]
Hi @stas00 @mayank31398 and @zcrypt0,
 
Yes, I confirm @stas00, and I agree with putting some kind of instructions there for people to generate their own int8-versions for any model. Regarding the checkpoint loading part, it is already added just for BLOOM and I am working on adding a general support for other models too, so that you can create your own checkpoint and easily load it with deepspeed-inference. 
Thanks,
Reza

**Comment by zcrypt0** [comment]
Thank you @stas00  and @RezaYazdaniAminabadi 

If I understand correctly, you simply change the dtype in the script, and add `save_mp_checkpoint_path` as if you were sharding the original weights in fp16.

Is it correct that you set the model name to `bigscience/bloom`?

I tried this same protocol several days ago on a **7x** A6000 node and ran into a tensor size mismatch:
```
RuntimeError: The size of tensor a (6144) must match the size of tensor b (14336) at non-singleton dimension 1
```

[Full Traceback](https://github.com/microsoft/DeepSpeed/pull/2217#issuecomment-1249776168)

I haven't ever tried a 7x GPU node with the fp16 weights, but I assumed it would work since 7 divides the number of BLOOM attention heads evenly. 

I did have a 14x GPU node working though.

Is there a fundamental limitation here with the 7x GPU case, or is it perhaps a bug in Deepspeed?

**Comment by stas00** [comment]
> Is it correct that you set the model name to bigscience/bloom?

you can call it anything you want as you're saving it into a custom model dump on your disc, you can set the saving path to say `/path/to/bloom-int8-7gpus`. The name of the repo is only important if you're trying to retrieve it from online, locally it's whatever you want it to be. It becomes important again should you upload it to the hub. and then it'll be `your_username/your_model_name`

> I tried this same protocol several days ago on a 7x A6000 node and ran into a tensor size mismatch

I will let @RezaYazdaniAminabadi reply to that as it's his domain.
