### ISSUE TITLE
Why is the throughput of DS-inference doubled when using 4 A100 GPUs compared to 8 A100 GPUs

### ISSUE THREAD

**Issue by DominickZhang** [huggingface/transformers-bloom-inference#59]
Hi,

Thank you for providing the valuable scripts for benchmark results of DS-inference. However, I am a bit confused about the values in the tables [here](https://github.com/huggingface/transformers-bloom-inference/blob/main/bloom-inference-scripts/README.md)

Specifically, when using 8 GPUs, the throughput of "accelerate int8" is similar to that of 4 GPUs. However, the throughput of "ds-inference int8" is doubled. I am wondering why there is such difference between accelerate and ds-inference.
![image](https://user-images.githubusercontent.com/16048179/221569763-13949a23-160d-42ca-b34c-f8b70aceb704.png)

![image](https://user-images.githubusercontent.com/16048179/221570029-6f1acfcc-0b43-4a02-a18d-1646219b418d.png)

Many thanks!

**Comment by mayank31398** [comment]
Hi @DominickZhang , both of the methods are quite different in nature.
accelerate int8 is [LLM.int8()](https://arxiv.org/abs/2208.07339)
ds-inference int8 is [ZeroQuant](https://arxiv.org/abs/2206.01861)

I don't think the insights from one can be generalized to the other one :)

**Comment by DominickZhang** [comment]
Thank you so much!

I think it is really interesting that increasing the number of GPUs benefits ds-inference more than accelerate, because the time cost for each prediction using ds-inference can be reduced in addition to the increase of the maximum batch size. :)

**Comment by mayank31398** [comment]
closing this :)
