### ISSUE TITLE
Multiple people querying MII issue

### ISSUE THREAD

**Issue by mayank31398** [huggingface/transformers-bloom-inference#6]
@stas00 
I have an issue.
If multiple people query BLOOM deployed with MII then, I run into event loop is already running issue.
I tried to fix this by awaiting the generate method but that just leads to MII getting stuck

**Comment by stas00** [comment]
I'd say this would be a question for the DeepSpeed team. You could tag them here, but it's probably the best to post about it directly at their Issues.
