### ISSUE TITLE
OOM of CUDA when using one GPU

### ISSUE THREAD

**Issue by xiongjun19** [huggingface/transformers-bloom-inference#60]
I my opinion the Parameter of the model should be stored In the cpu when using zero inference, but I always get OOM error of CUDA

**Comment by mayank31398** [comment]
why do you think so?
Can you tell me which script you are running?
ZeRO doesn't mean params on CPU. You will need to use CPU offloading for that.
But even, then 176B can't be run on 1 GPU (I think, you will have to try it out).

**Comment by richarddwang** [comment]
Hi, I have sucessfully inference Bloomz-175b on a 40GB A100 with zero-inference and cpu_offload activated. (I am using `bloom-ds-zero-inferency.py`) As to @xiongjun19's question, zero_infernece places only parameters needed for current computation in GPU, and place other parameters in CPU. You can think that it will load a layer of model in GPU and place other layers in CPU. So you still need enough GPU memory for the computation.

**Comment by xiongjun19** [comment]
> Hi, I have sucessfully inference Bloomz-175b on a 40GB A100 with zero-inference and cpu_offload activated. (I am using `bloom-ds-zero-inferency.py`) As to @xiongjun19's question, zero_infernece places only parameters needed for current computation in GPU, and place other parameters in CPU. You can think that it will load a layer of model in GPU and place other layers in CPU. So you still need enough GPU memory for the computation.

Thank you.  I will try later on  a 40GB A100

**Comment by mayank31398** [comment]
Awesome. closing this!
