### ISSUE TITLE
how to run the server?

### ISSUE THREAD

**Issue by raihan0824** [huggingface/transformers-bloom-inference#64]
how to run the server to be able to run the UI?

**Comment by mayank31398** [comment]
You can use the [Makefile](https://github.com/huggingface/transformers-bloom-inference/blob/main/Makefile).
`make bloom-560m-cpu` will bring up the 560m bloom model.
There are other examples in there too.
Otherwise you can also use the dockerfile.

**Comment by mayank31398** [comment]
closing this
