### ISSUE TITLE
Is there a way to initialize a random weight for

### ISSUE THREAD

**Issue by PannenetsF** [huggingface/transformers-bloom-inference#74]
Hi! Thank you for the wonderful work of LLM inference.

For now, I am profiling the performance of each part of the code, but I do not care about the output. And the checkpoint loading takes too much time, so I wonder if is there a way to load empty ckpt or just initialize the model with random ones.

**Comment by mayank31398** [comment]
Hey @PannenetsF 
Thanks a lot for trying this.
I think the benchmark might be better if you use this repo: https://github.com/bigcode-project/bigcode-inference-benchmark/
Thanks :)

**Comment by PannenetsF** [comment]
Thanks for the response, I will try it out later! @mayank31398

**Comment by mayank31398** [comment]
closing this.
