### ISSUE TITLE
concurrent requests

### ISSUE THREAD

**Issue by ustclan** [huggingface/transformers-bloom-inference#75]
I read in the README: "Please note that the serving method is synchronous and users have to wait in queue until the preceding requests have been processed. "

Is there any way to support concurrent requests? As it may be waste of resource to fire requests one by one.

**Comment by mayank31398** [comment]
Hi @ustclan great question.
This repository is not meant for serving at scale but is rather meant for quick experimentation by an individual or a really small team.
If you want support for concurrent requests, please check out https://github.com/huggingface/text-generation-inference

**Comment by ustclan** [comment]
> 

thx!
