### ISSUE TITLE
Can not generate text correctly after loading an int8 model

### ISSUE THREAD

**Issue by moonlightian** [huggingface/transformers-bloom-inference#80]
Hi,
I am confused about how to reload a quantized model.
when I load model with the code below ,it could generate texts normally
```
model = AutoModelForCausalLM.from_pretrained(
    'bigscience/bloom-7b1',
    device_map='auto',
    torch_dtype=torch.int8,
    load_in_8bit=True,
    )
```
while I save this inference model with `model.save_pretrained(output_dir, state_dict=state_dict)` and reload with
`model = AutoModelForCausalLM.from_pretrained(
    CHECKPOINT_PATH, 
    device_map='auto',
    )`
the text generated was meaningless and it seems that some weights of the model checkpoint were not used when initializing BloomForCausalLM, warnings like this:
`['transformer.h.4.self_attention.dense.SCB', 'transformer.h.18.mlp.dense_4h_to_h.SCB', 'transformer.h.2.mlp.dense_h_to_4h.SCB', 'transformer.h.24.mlp.dense_4h_to_h.SCB', 'transformer.h.17.self_attention.query_key_value.SCB', 'transformer.h.25.self_attention.query_key_value.SCB', 'transformer.h.14.self_attention.dense.SCB', 'transformer.h.28.mlp.dense_4h_to_h.SCB', 'transformer.h.6.mlp.dense_4h_to_h.SCB', 'transformer.h.3.self_attention.query_key_value.SCB', 'transformer.h.13.self_attention.dense.SCB', 'transformer.h.2.self_attention.dense.SCB', 'transformer.h.11.mlp.dense_4h_to_h.SCB', 'transformer.h.6.mlp.dense_h_to_4h.SCB', 'transformer.h.13.mlp.dense_h_to_4h.SCB', 'transformer.h.19.mlp.dense_h_to_4h.SCB', 'transformer.h.19.self_attention.dense.SCB', 'transformer.h.29.self_attention.dense.SCB', 'transformer.h.11.mlp.dense_h_to_4h.SCB', 'transformer.h.14.mlp.dense_h_to_4h.SCB', 'transformer.h.11.self_attention.query_key_value.SCB', 'transformer.h.19.mlp.dense_4h_to_h.SCB', 'transformer.h.0.mlp.dense_h_to_4h.SCB', 'transformer.h.3.self_attention.dense.SCB', 'transformer.h.20.mlp.dense_h_to_4h.SCB', 'transformer.h.29.mlp.dense_4h_to_h.SCB', 'transformer.h.22.self_attention.dense.SCB', 'transformer.h.12.mlp.dense_h_to_4h.SCB', 'transformer.h.29.mlp.dense_h_to_4h.SCB', 'transformer.h.23.self_attention.query_key_value.SCB', 'transformer.h.7.self_attention.dense.SCB', 'transformer.h.22.mlp.dense_h_to_4h.SCB', 'transformer.h.21.mlp.dense_4h_to_h.SCB', 'transformer.h.21.self_attention.dense.SCB', 'transformer.h.8.mlp.dense_h_to_4h.SCB', 'transformer.h.24.mlp.dense_h_to_4h.SCB', 'transformer.h.1.mlp.dense_h_to_4h.SCB', 'transformer.h.5.self_attention.dense.SCB', 'transformer.h.18.self_attention.dense.SCB', 'transformer.h.3.mlp.dense_4h_to_h.SCB', 'transformer.h.14.self_attention.query_key_value.SCB', 'transformer.h.15.self_attention.query_key_value.SCB', 'transformer.h.21.mlp.dense_h_to_4h.SCB', 'transformer.h.5.mlp.dense_h_to_4h.SCB', 'transformer.h.20.mlp.dense_4h_to_h.SCB', 'transformer.h.7.mlp.dense_4h_to_h.SCB', 'transformer.h.16.mlp.dense_h_to_4h.SCB', 'transformer.h.5.self_attention.query_key_value.SCB', 'transformer.h.10.self_attention.dense.SCB', 'transformer.h.24.self_attention.dense.SCB', 'transformer.h.10.mlp.dense_4h_to_h.SCB', 'transformer.h.15.mlp.dense_h_to_4h.SCB', 'transformer.h.26.mlp.dense_4h_to_h.SCB', 'transformer.h.6.self_attention.query_key_value.SCB', 'transformer.h.26.mlp.dense_h_to_4h.SCB', 'transformer.h.27.self_attention.dense.SCB', 'transformer.h.7.mlp.dense_h_to_4h.SCB', 'transformer.h.21.self_attention.query_key_value.SCB', 'transformer.h.0.self_attention.query_key_value.SCB', 'transformer.h.23.mlp.dense_4h_to_h.SCB', 'transformer.h.10.mlp.dense_h_to_4h.SCB', 'transformer.h.17.self_attention.dense.SCB', 'transformer.h.8.mlp.dense_4h_to_h.SCB', 'transformer.h.12.mlp.dense_4h_to_h.SCB', 'transformer.h.7.self_attention.query_key_value.SCB', 'transformer.h.16.self_attention.query_key_value.SCB', 'transformer.h.28.self_attention.dense.SCB', 'transformer.h.3.mlp.dense_h_to_4h.SCB', 'transformer.h.4.mlp.dense_h_to_4h.SCB', 'transformer.h.9.self_attention.query_key_value.SCB', 'transformer.h.15.self_attention.dense.SCB', 'transformer.h.0.self_attention.dense.SCB', 'transformer.h.16.mlp.dense_4h_to_h.SCB', 'transformer.h.1.mlp.dense_4h_to_h.SCB', 'transformer.h.13.mlp.dense_4h_to_h.SCB', 'transformer.h.11.self_attention.dense.SCB', 'transformer.h.26.self_attention.query_key_value.SCB', 'transformer.h.28.self_attention.query_key_value.SCB', 'transformer.h.13.self_attention.query_key_value.SCB', 'transformer.h.22.self_attention.query_key_value.SCB', 'transformer.h.26.self_attention.dense.SCB', 'transformer.h.29.self_attention.query_key_value.SCB', 'transformer.h.19.self_attention.query_key_value.SCB', 'transformer.h.12.self_attention.query_key_value.SCB', 'transformer.h.27.mlp.dense_4h_to_h.SCB', 'transformer.h.25.self_attention.dense.SCB', 'transformer.h.2.self_attention.query_key_value.SCB', 'transformer.h.10.self_attention.query_key_value.SCB', 'transformer.h.9.mlp.dense_4h_to_h.SCB', 'transformer.h.9.self_attention.dense.SCB', 'transformer.h.20.self_attention.query_key_value.SCB', 'transformer.h.9.mlp.dense_h_to_4h.SCB', 'transformer.h.27.mlp.dense_h_to_4h.SCB', 'transformer.h.14.mlp.dense_4h_to_h.SCB', 'transformer.h.8.self_attention.query_key_value.SCB', 'transformer.h.24.self_attention.query_key_value.SCB', 'transformer.h.22.mlp.dense_4h_to_h.SCB', 'transformer.h.4.mlp.dense_4h_to_h.SCB', 'transformer.h.5.mlp.dense_4h_to_h.SCB', 'transformer.h.1.self_attention.dense.SCB', 'transformer.h.1.self_attention.query_key_value.SCB', 'transformer.h.6.self_attention.dense.SCB', 'transformer.h.12.self_attention.dense.SCB', 'transformer.h.23.self_attention.dense.SCB', 'transformer.h.17.mlp.dense_h_to_4h.SCB', 'transformer.h.23.mlp.dense_h_to_4h.SCB', 'transformer.h.8.self_attention.dense.SCB', 'transformer.h.25.mlp.dense_4h_to_h.SCB', 'transformer.h.20.self_attention.dense.SCB', 'transformer.h.25.mlp.dense_h_to_4h.SCB', 'transformer.h.28.mlp.dense_h_to_4h.SCB', 'transformer.h.4.self_attention.query_key_value.SCB', 'transformer.h.18.self_attention.query_key_value.SCB', 'transformer.h.2.mlp.dense_4h_to_h.SCB', 'transformer.h.18.mlp.dense_h_to_4h.SCB', 'transformer.h.17.mlp.dense_4h_to_h.SCB', 'transformer.h.0.mlp.dense_4h_to_h.SCB', 'transformer.h.15.mlp.dense_4h_to_h.SCB', 'transformer.h.27.self_attention.query_key_value.SCB', 'transformer.h.16.self_attention.dense.SCB']`
How could I load a quantized model in a right way?
Looking forward to your reply，Thank you~

**Comment by mayank31398** [comment]
depends on what the model is.
don't specify `dtype`. load_in_8_bit is enough.
This will use `LLM.int8()` for quantization

**Comment by moonlightian** [comment]
> depends on what the model is. don't specify `dtype`. load_in_8_bit is enough. This will use `LLM.int8()` for quantization] basically:
> 
> ```python
>         if args.dtype == torch.int8:
>             # using LLM.int8()
>             kwargs["load_in_8bit"] = True
>         else:
>             kwargs["torch_dtype"] = args.dtype
> ```

Thanks a lot for your reply!
Follow your settings, I initial and saved quantized modle with:
`model_name = 'bigscience/bloom-7b1'

model = AutoModelForCausalLM.from_pretrained(
    'bigscience/bloom-7b1', 
    device_map="auto",
    load_in_8bit=True,
    )
output_dir = '/tmp/modelhub/Bloom/3'
state_dict = model.state_dict()
model.save_pretrained(output_dir, state_dict=state_dict)`
This model can generate texts normally like, but it warns me that
"You are calling `save_pretrained` to a 8-bit converted model you may likely encounter unexepected behaviors."
![image](https://user-images.githubusercontent.com/49636631/233889723-5a41decb-d721-4aa7-8d61-b99a560a700d.png)

But unfortunately，I reload the model saved before with codes like:
`CHECKPOINT_PATH = '/tmp/modelhub/Bloom/3/'
model = AutoModelForCausalLM.from_pretrained(
    CHECKPOINT_PATH, 
    device_map='auto',
    )`
It could not generate texts any more which confused me a lot. Is there some mistakes have I made during saving quantized model or reloding models? How could I get rid of these problems?
![image](https://user-images.githubusercontent.com/49636631/233890097-e7b31a2c-4de3-4faa-ade8-817186943d13.png)

Looking forward your reply.

**Comment by mayank31398** [comment]
Yeah, you aren't supposed to use `save_pretrained` with LLM.int8() method of quantization.
While loading, you can just quantize the non-quant checkpoint by specifying `load_in_8bit`

**Comment by mayank31398** [comment]
closing this
