### ISSUE TITLE
Unable to reload a quantized model

### ISSUE THREAD

**Issue by moonlightian** [huggingface/transformers-bloom-inference#85]
After setting `load_in_8bit=True` for .from_pretrained() function and get model quantized. How should I save this model and get it reloaded with .from_pretrained() again? And make all weights be loaded normally

**Comment by moonlightian** [comment]
and I found that after quantization, some weights endwith '.SCB' are stored into the state_dict which are not able to be loaded by AutoModelForCausalLM. I wonder how could I load these weights into the model, it seems that these weigts are related to Quantization

**Comment by moonlightian** [comment]
![image](https://user-images.githubusercontent.com/49636631/234842900-741de3cf-1ceb-4aa6-a7a8-6a2abe4d37e0.png)
after save_pretrained(), I found weights endwith '.SCB' in pytorch_modl.bin.index.json, which are not able to reload into AutoModelForCausalLM. How could I get rid of these problems?

**Comment by mayank31398** [comment]
you are not supposed to save this model and reload again.
`load_in_8bit` is supposed to be used on the fly.

**Comment by moonlightian** [comment]
> you are not supposed to save this model and reload again. `load_in_8bit` is supposed to be used on the fly.

Thanks a lot for your reply，still looking forward for a method for reloading
