### ISSUE TITLE
why no use deepspeed.init_inference in zero benchmark

### ISSUE THREAD

**Issue by tingshua-yts** [huggingface/transformers-bloom-inference#86]
from the source code，when use zero benchmark，is not use deepspeed.init_inference
```python
# ds_zero.py
self.model = deepspeed.initialize(model=self.model, config_params=ds_config)[0]
```
if not use deepspeed.init_inference there is no transformer kernel optimze, is it expected?

**Comment by mayank31398** [comment]
hey in zero_inference, we are not using fused kernels but rather the [ZeRO sharding strategy](https://arxiv.org/abs/1910.02054).
This is ideally meant for training and not inference but we still try it with inference.

**Comment by mayank31398** [comment]
closing this
