### ISSUE TITLE
question regarding the float16 and bfloat

### ISSUE THREAD

**Issue by allanj** [huggingface/transformers-bloom-inference#87]
https://github.com/huggingface/transformers-bloom-inference/blob/7bea3526d8270b4aeeefecc57d7d7d638e2bbe0e/bloom-inference-scripts/bloom-ds-inference.py#L121-L137

In this code the first argument in `with deepspeed.OnDevice(dtype=dtype, device="meta"): ` we use `float16`, while 
```python3
model = AutoModelForCausalLM.from_config(config, torch_dtype=torch.bfloat16)
```
here we use `bfloat16`.

I wonder why we should have this inconsistency?

**Comment by mayank31398** [comment]
@allanj it doesn't really matter.
when specifying `meta`, it only does memory allocation with empty tensors and both are 16-bit.
